export { default as Toast } from 'antd-mobile/es/toast/index'
export { default as WingBlank } from 'antd-mobile/es/wing-blank'
export { default as Button } from 'antd-mobile/es/button'
export { default as Icon } from 'antd-mobile/es/icon'
export { default as Modal } from 'antd-mobile/es/modal'